<a href="https://www.kaggle.com/code/avinashrola/food-prices-india?scriptVersionId=107809695" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/india-food-prices/wfp_food_prices_ind.csv

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv('/kaggle/input/india-food-prices/wfp_food_prices_ind.csv')
data.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3552: DtypeWarning: Columns (4,5,12,13) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
0,#date,#adm1+name,#adm2+name,#loc+market+name,#geo+lat,#geo+lon,#item+type,#item+name,#item+unit,#item+price+flag,#item+price+type,#currency,#value,#value+usd
1,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,cereals and tubers,Rice,KG,actual,Retail,INR,8.0,0.2545
2,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,cereals and tubers,Wheat,KG,actual,Retail,INR,5.0,0.159
3,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,miscellaneous food,Sugar,KG,actual,Retail,INR,13.5,0.4294
4,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,oil and fats,Oil (mustard),KG,actual,Retail,INR,31.0,0.986

In [4]:
data = data.iloc[1: , : ]
data.head()

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
1,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,cereals and tubers,Rice,KG,actual,Retail,INR,8.0,0.2545
2,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,cereals and tubers,Wheat,KG,actual,Retail,INR,5.0,0.159
3,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,miscellaneous food,Sugar,KG,actual,Retail,INR,13.5,0.4294
4,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,oil and fats,Oil (mustard),KG,actual,Retail,INR,31.0,0.986
5,1994-01-15,Gujarat,Ahmadabad,Ahmedabad,23.033333,72.616667,cereals and tubers,Rice,KG,actual,Retail,INR,6.8,0.2163

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172017 entries, 1 to 172017
Data columns (total 14 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   date       172017 non-null  object
 1   admin1     171228 non-null  object
 2   admin2     171228 non-null  object
 3   market     172017 non-null  object
 4   latitude   171228 non-null  object
 5   longitude  171228 non-null  object
 6   category   172017 non-null  object
 7   commodity  172017 non-null  object
 8   unit       172017 non-null  object
 9   priceflag  172017 non-null  object
 10  pricetype  172017 non-null  object
 11  currency   172017 non-null  object
 12  price      172017 non-null  object
 13  usdprice   172017 non-null  object
dtypes: object(14)
memory usage: 18.4+ MB

In [6]:
# check the null records
data.isnull().sum()

date           0
admin1       789
admin2       789
market         0
latitude     789
longitude    789
category       0
commodity      0
unit           0
priceflag      0
pricetype      0
currency       0
price          0
usdprice       0
dtype: int64

In [7]:
# Drop null values
data.dropna(inplace=True)

In [8]:
# check the null records
data.isnull().sum()

date         0
admin1       0
admin2       0
market       0
latitude     0
longitude    0
category     0
commodity    0
unit         0
priceflag    0
pricetype    0
currency     0
price        0
usdprice     0
dtype: int64

In [9]:
data.describe()

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
count,171228,171228,171228,171228,171228,171228,171228,171228,171228,171228,171228,171228,171228.0,171228.0000
unique,343,31,158,164,219,215,6,23,3,1,2,1,28309.0,43192.0000
top,2022-05-15,Uttar Pradesh,Mumbai city,Mumbai,18.975,72.825833,oil and fats,Rice,KG,actual,Retail,INR,20.0,0.2667
freq,3290,13173,4364,4364,2920,2920,41638,12392,159942,171228,168951,171228,1612.0,348.0000

In [10]:
data.head()

,date,admin1,admin2,market,latitude,longitude,category,commodity,unit,priceflag,pricetype,currency,price,usdprice
1,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,cereals and tubers,Rice,KG,actual,Retail,INR,8.0,0.2545
2,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,cereals and tubers,Wheat,KG,actual,Retail,INR,5.0,0.159
3,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,miscellaneous food,Sugar,KG,actual,Retail,INR,13.5,0.4294
4,1994-01-15,Delhi,Delhi,Delhi,28.666667,77.216667,oil and fats,Oil (mustard),KG,actual,Retail,INR,31.0,0.986
5,1994-01-15,Gujarat,Ahmadabad,Ahmedabad,23.033333,72.616667,cereals and tubers,Rice,KG,actual,Retail,INR,6.8,0.2163

In [11]:
data['admin1'].value_counts()

Uttar Pradesh          13173
Bihar                  11337
Madhya Pradesh         11320
Tamil Nadu             10626
Orissa                 10382
Maharashtra            10077
Karnataka               8541
Rajasthan               8397
Haryana                 7985
Kerala                  7637
Gujarat                 7257
West Bengal             7143
Punjab                  6490
Himachal Pradesh        6083
Telangana               5225
Delhi                   4345
Jharkhand               4285
Meghalaya               3556
Andhra Pradesh          3549
Uttarakhand             3530
Assam                   2588
Andaman and Nicobar     2380
Tripura                 2271
Chandigarh              2241
Nagaland                2190
Puducherry              2152
Chhattisgarh            2069
Goa                     1966
Mizoram                 1808
Sikkim                   400
Manipur                  225
Name: admin1, dtype: int64

In [12]:
data['admin2'].value_counts()

Mumbai city        4364
Delhi              4345
Chennai            4080
Patna              4043
Bikaner            3205
                   ...
Vadodara            231
Dhanbad             231
Purba Singhbhum     231
West Imphal         225
Kohima              123
Name: admin2, Length: 158, dtype: int64

In [13]:
data['category'].value_counts()

oil and fats             41638
cereals and tubers       40581
miscellaneous food       33736
pulses and nuts          29478
vegetables and fruits    16786
milk and dairy            9009
Name: category, dtype: int64

In [14]:
data['commodity'].value_counts()

Rice                   12392
Sugar                  11799
Wheat                  11225
Oil (mustard)          10783
Potatoes                8767
Onions                  8717
Wheat flour             8197
Salt (iodised)          8076
Tomatoes                8069
Milk (pasteurized)      8018
Lentils (masur)         7872
Lentils                 7610
Tea (black)             7504
Oil (sunflower)         7116
Lentils (moong)         6511
Lentils (urad)          6487
Sugar (jaggery/gur)     6357
Oil (groundnut)         6335
Ghee (vanaspati)        6211
Oil (palm)              5986
Oil (soybean)           5207
Chickpeas                998
Milk                     991
Name: commodity, dtype: int64

In [15]:
data['usdprice'].astype('str')

1         0.2545
2          0.159
3         0.4294
4          0.986
5         0.2163
           ...
172013    1.4177
172014    1.5881
172015    1.2785
172016    0.3319
172017     0.716
Name: usdprice, Length: 171228, dtype: object

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 171228 entries, 1 to 172017
Data columns (total 14 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   date       171228 non-null  object
 1   admin1     171228 non-null  object
 2   admin2     171228 non-null  object
 3   market     171228 non-null  object
 4   latitude   171228 non-null  object
 5   longitude  171228 non-null  object
 6   category   171228 non-null  object
 7   commodity  171228 non-null  object
 8   unit       171228 non-null  object
 9   priceflag  171228 non-null  object
 10  pricetype  171228 non-null  object
 11  currency   171228 non-null  object
 12  price      171228 non-null  object
 13  usdprice   171228 non-null  object
dtypes: object(14)
memory usage: 19.6+ MB